wandb_version: 1

DATA_DIRECTORY_SOURCE:
  desc: null
  value: ../ADVENT/data/Cityscapes
DATA_DIRECTORY_TARGET:
  desc: null
  value: /media/data/hlim/IntraDA/ADVENT/data/Cityscapes
DATA_LIST_SOURCE:
  desc: null
  value: ../entropy_rank/easy_split_FDA_on.txt
DATA_LIST_TARGET:
  desc: null
  value: ../entropy_rank/hard_split_FDA_on.txt
EXP_NAME:
  desc: null
  value: CityscapesEasy2CityscapesHard_DeepLabv2_AdvEnt_on
EXP_ROOT:
  desc: null
  value: /media/data/hlim/IntraDA/ADVENT/experiments
EXP_ROOT_LOGS:
  desc: null
  value: /media/data/hlim/IntraDA/ADVENT/experiments/logs
EXP_ROOT_SNAPSHOT:
  desc: null
  value: /media/data/hlim/IntraDA/ADVENT/experiments/snapshots
FDA_mode:
  desc: null
  value: 'on'
GPU_ID:
  desc: null
  value: 0
NUM_CLASSES:
  desc: null
  value: 19
NUM_WORKERS:
  desc: null
  value: 1
SOURCE:
  desc: null
  value: CityscapesEasy
TARGET:
  desc: null
  value: CityscapesHard
TEST:
  desc: null
  value:
    BATCH_SIZE_TARGET: 1
    IMG_MEAN:
    - 104.00698852539062
    - 116.66876983642578
    - 122.67891693115234
    INFO_TARGET: /media/data/hlim/IntraDA/ADVENT/advent/dataset/cityscapes_list/info.json
    INPUT_SIZE_TARGET:
    - 1024
    - 512
    MODE: best
    MODEL:
    - DeepLabv2
    MODEL_WEIGHT:
    - 1.0
    MULTI_LEVEL:
    - true
    OUTPUT_SIZE_TARGET:
    - 2048
    - 1024
    RESTORE_FROM:
    - ''
    SET_TARGET: val
    SNAPSHOT_DIR:
    - ''
    SNAPSHOT_MAXITER: 120000
    SNAPSHOT_STEP: 2000
    WAIT_MODEL: true
TRAIN:
  desc: null
  value:
    BATCH_SIZE_SOURCE: 1
    BATCH_SIZE_TARGET: 1
    DA_METHOD: AdvEnt
    EARLY_STOP: 120000
    IGNORE_LABEL: 255
    IMG_MEAN:
    - 104.00698852539062
    - 116.66876983642578
    - 122.67891693115234
    INFO_SOURCE: ''
    INFO_TARGET: /media/data/hlim/IntraDA/ADVENT/advent/dataset/cityscapes_list/info.json
    INPUT_SIZE_SOURCE:
    - 1024
    - 512
    INPUT_SIZE_TARGET:
    - 1024
    - 512
    LAMBDA_ADV_AUX: 0.0002
    LAMBDA_ADV_MAIN: 0.001
    LAMBDA_ENT_AUX: 0.0002
    LAMBDA_ENT_MAIN: 0.001
    LAMBDA_SEG_AUX: 0.1
    LAMBDA_SEG_MAIN: 1.0
    LEARNING_RATE: 0.00025
    LEARNING_RATE_D: 0.0001
    MAX_ITERS: 250000
    MODEL: DeepLabv2
    MOMENTUM: 0.9
    MULTI_LEVEL: true
    POWER: 0.9
    RANDOM_SEED: 1234
    RESTORE_FROM: ../ADVENT/pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
    SAVE_PRED_EVERY: 2000
    SET_SOURCE: all
    SET_TARGET: train
    SNAPSHOT_DIR: /media/data/hlim/IntraDA/ADVENT/experiments/snapshots/CityscapesEasy2CityscapesHard_DeepLabv2_AdvEnt_on
    TENSORBOARD_LOGDIR: /media/data/hlim/IntraDA/ADVENT/experiments/logs/tensorboard/CityscapesEasy2CityscapesHard_DeepLabv2_AdvEnt_on
    TENSORBOARD_VIZRATE: 100
    WEIGHT_DECAY: 0.0005
_wandb:
  desc: null
  value:
    cli_version: 0.9.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
cfg:
  desc: null
  value: ./intrada_FDA_on.yml
exp_suffix:
  desc: null
  value: null
random_train:
  desc: null
  value: false
tensorboard:
  desc: null
  value: true
viz_every_iter:
  desc: null
  value: null
